### ISSUE TITLE
New version of plugin throwing errors:

### ISSUE THREAD

**Issue by Danimal4326** [madchicken/homebridge-comelit-icona#7]
[1/30/2023, 2:51:44 PM] [Comelit] Triggered SET TargetPosition:0
[1/30/2023, 2:51:44 PM] [Comelit] Connecting to comelit-doorbell:64100
[1/30/2023, 2:51:44 PM] [Comelit] connected
[1/30/2023, 2:51:44 PM] [Comelit] Writing bytes to socket:
00 06 10 00 00 00 00 00 cd ab 01 00 07 00 00 00         ················
55 41 55 54 41 1f 00 00                                 UAUTA···
[1/30/2023, 2:51:44 PM] [Comelit] Read bytes from socket (size: 12):
cd ab 02 00 04 00 00 00 41 1f 00 00                     ········A···
[1/30/2023, 2:51:44 PM] [Comelit] Opened channel UAUT, sequence is 2 and requestId is 1f 41
[1/30/2023, 2:51:44 PM] [Comelit] Writing bytes to socket:
00 06 6c 00 41 1f 00 00 7b 22 6d 65 73 73 61 67         ··l·A···{"messag
65 22 3a 22 61 63 63 65 73 73 22 2c 22 75 73 65         e":"access","use
<TOKEN REDACTED>
73 61 67 65 2d 74 79 70 65 22 3a 22 72 65 71 75         sage-type":"requ
65 73 74 22 2c 22 6d 65 73 73 61 67 65 2d 69 64         est","message-id
22 3a 32 7d                                             ":2}
[1/30/2023, 2:51:44 PM] [Comelit] Read bytes from socket (size: 116):
7b 22 6d 65 73 73 61 67 65 22 3a 22 61 63 63 65         {"message":"acce
73 73 22 2c 22 6d 65 73 73 61 67 65 2d 74 79 70         ss","message-typ
65 22 3a 22 72 65 73 70 6f 6e 73 65 22 2c 22 6d         e":"response","m
65 73 73 61 67 65 2d 69 64 22 3a 32 2c 22 72 65         essage-id":2,"re
73 70 6f 6e 73 65 2d 63 6f 64 65 22 3a 32 30 30         sponse-code":200
2c 22 72 65 73 70 6f 6e 73 65 2d 73 74 72 69 6e         ,"response-strin
67 22 3a 22 41 63 63 65 73 73 20 47 72 61 6e 74         g":"Access Grant
65 64 22 7d                                             ed"}
[1/30/2023, 2:51:44 PM] [Comelit] Writing bytes to socket:
00 06 04 00 00 00 00 00 ef 01 03 00                     ············
[1/30/2023, 2:51:44 PM] [Comelit] Read bytes from socket (size: 12):
ef 01 04 00 04 00 00 00 00 00 01 00                     ············
[1/30/2023, 2:51:44 PM] [Comelit] END response received with sequence number 4
[1/30/2023, 2:51:44 PM] [Comelit] Closed channel UAUT, sequence id is 4 and requestId is 1f 41
[1/30/2023, 2:51:44 PM] [Comelit] Writing bytes to socket:
00 06 1e 00 00 00 00 00 cd ab 01 00 07 00 00 00         ················
43 54 50 50 42 1f 00 00 0a 00 00 00 30 30 30 30         CTPPB·······0000
30 30 30 30 31 00                                       00001·
[1/30/2023, 2:51:44 PM] [Comelit] Read bytes from socket (size: 12):
cd ab 02 00 04 00 00 00 42 1f 00 00                     ········B···
[1/30/2023, 2:51:44 PM] [Comelit] Opened channel CTPP, sequence is 2 and requestId is 1f 42
[1/30/2023, 2:51:44 PM] [Comelit] Writing bytes to socket:
00 06 34 00 42 1f 00 00 c0 18 5c 8b 2b 73 00 11         ··4·B·····\·+s··
00 40 ac 23 30 30 30 30 30 30 30 30 31 00 10 0e         ·@·#000000001···
00 00 00 00 ff ff ff ff 30 30 30 30 30 30 30 30         ········00000000
31 00 30 30 30 30 30 30 30 30 00 00                     1·00000000··
[1/30/2023, 2:51:44 PM] [Comelit] Read bytes from socket (size: 32):
00 18 dc 8b 73 2c 00 00 ff ff ff ff 30 30 30 30         ····s,······0000
30 30 30 30 00 00 30 30 30 30 30 30 30 30 31 00         0000··000000001·
[1/30/2023, 2:51:44 PM] [Comelit] Open door: ^@^X܋s,^@^@����00000000^@^@000000001^@
[1/30/2023, 2:51:44 PM] [Comelit] CTPP 1:
{"requestId":8002,"sequence":-1,"type":0}
[1/30/2023, 2:51:45 PM] [Comelit] Read bytes from socket (size: 48):
60 18 dc 8b 73 2c 00 10 00 41 ac 23 30 30 30 30         `···s,···A·#0000
30 30 30 30 31 00 00 00 ff ff ff ff 30 30 30 30         00001·······0000
30 30 30 30 00 00 30 30 30 30 30 30 30 30 31 00         0000··000000001·
[1/30/2023, 2:51:45 PM] [Comelit] Open door: `^X܋s,^@^P^@A�#000000001^@^@^@����00000000^@^@000000001^@
[1/30/2023, 2:51:45 PM] [Comelit] CTPP 2:
{"requestId":8002,"sequence":-1,"type":0}
[1/30/2023, 2:51:45 PM] [Comelit] ICONA Client initialized
[1/30/2023, 2:51:45 PM] [Comelit] Device is a door, sending openDoor command
[1/30/2023, 2:51:45 PM] [Comelit] Writing bytes to socket:
00 06 1f 00 42 1f 00 00 00 5c 8b 2c 74 00 00 ff         ····B····\·,t···
ff ff ff 30 30 30 30 30 30 30 30 31 00 30 30 30         ···000000001·000
30 30 30 30 30 00 00                                    00000··
[1/30/2023, 2:51:45 PM] [Comelit] Writing bytes to socket:
00 06 1f 00 42 1f 00 00 20 5c 8b 2c 74 00 00 ff         ····B··· \·,t···
ff ff ff 30 30 30 30 30 30 30 30 31 00 30 30 30         ···000000001·000
30 30 30 30 30 00 00                                    00000··
[1/30/2023, 2:51:45 PM] [Comelit] Writing bytes to socket:
00 06 30 00 42 1f 00 00 c0 18 70 ab 29 9f 00 0d         ··0·B·····p·)···
00 2d 30 30 30 30 30 31 30 30 00 00 01 00 00 00         ·-00000100······
ff ff ff ff 30 30 30 30 30 30 30 30 31 00 30 30         ····000000001·00
30 30 30 31 30 30 00 00                                 000100··
[1/30/2023, 2:51:45 PM] [Comelit] Read bytes from socket (size: 32):
00 18 f0 ab 9f 2a 00 00 ff ff ff ff 30 30 30 30         ·····*······0000
30 31 30 30 00 00 30 30 30 30 30 30 30 30 31 00         0100··000000001·
[1/30/2023, 2:51:45 PM] [Comelit] Open door: ^@^X�*^@^@����00000100^@^@000000001^@
[1/30/2023, 2:51:45 PM] [Comelit] {"requestId":8002,"sequence":-1,"type":0}
[1/30/2023, 2:51:45 PM] [Comelit] Read bytes from socket (size: 48):
60 18 dc 8b 73 2c 00 10 00 41 ac 23 30 30 30 30         `···s,···A·#0000
30 30 30 30 31 00 00 00 ff ff ff ff 30 30 30 30         00001·······0000
30 30 30 30 00 00 30 30 30 30 30 30 30 30 31 00         0000··000000001·
[1/30/2023, 2:51:45 PM] [Comelit] Open door: `^X܋s,^@^P^@A�#000000001^@^@^@����00000000^@^@000000001^@
[1/30/2023, 2:51:45 PM] [Comelit] {"requestId":8002,"sequence":-1,"type":0}
[1/30/2023, 2:51:45 PM] [Comelit] Writing bytes to socket:
00 06 1e 00 42 1f 00 00 00 5c 8b 2c 74 00 00 ff         ····B····\·,t···
ff ff ff 30 30 30 30 30 30 30 30 31 00 30 30 30         ···000000001·000
30 30 31 30 30 00                                       00100·
[1/30/2023, 2:51:45 PM] [Comelit] Writing bytes to socket:
00 06 1e 00 42 1f 00 00 20 5c 8b 2c 74 00 00 ff         ····B··· \·,t···
ff ff ff 30 30 30 30 30 30 30 30 31 00 30 30 30         ···000000001·000
30 30 31 30 30 00                                       00100·
[1/30/2023, 2:51:45 PM] [homebridge-comelit-icona] This plugin threw an error from the characteristic 'Lock Target State': Unhandled error thrown inside w
rite handler for characteristic: Cannot read properties of undefined (reading 'type'). See https://homebridge.io/w/JtMGR for more info.
[1/30/2023, 2:51:45 PM] [homebridge-comelit-icona] TypeError: Cannot read properties of undefined (reading 'type')
    at DoorAccessory.<anonymous> (/usr/lib/node_modules/homebridge-comelit-icona/src/accessories/door-accessory.ts:136:28)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-comelit-icona/dist/accessories/door-accessory.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Danimal4326** [comment]
fixed with latest release
